ALTER TABLE users
ADD COLUMN IF NOT EXISTS display_name VARCHAR(80),
ADD COLUMN IF NOT EXISTS bio VARCHAR(300),
ADD COLUMN IF NOT EXISTS avatar_url TEXT;

UPDATE users
SET display_name = username
WHERE display_name IS NULL;
